### ISSUE TITLE
Provide Cornish language version

### ISSUE THREAD

**Issue by matthew-andrews** [wheresrhys/promise-throttle#1]
We use ‘dreckly’ or ‘dreckley’.

**Comment by wheresrhys** [comment]
from my devonshire friend

> Btw, pronounciation: 'Drecly'

When I can be bothered I'm gonna add some example usage to the documentation e.g. 

> e.g. I'll wash the dishes drecly, my lover

**Comment by matthew-andrews** [comment]
yup could be solved with a pronunciation guide.

**Comment by wheresrhys** [comment]
Fixed https://www.npmjs.com/package/directly#about-the-name 

cc @panoapps

**Comment by matthew-andrews** [comment]
This meets the CoS.

**Comment by wheresrhys** [comment]
Other than it got done a little too directly

**Comment by matthew-andrews** [comment]
where you to?

**Comment by leafrogers** [comment]
:trophy:
